[workspace]
resolver = "3"
members = [
    "crates/rue_core",
    "crates/rue_eval",
    "crates/rue_nav",
    "crates/rue_perft",
    "crates/rue_search",
    "crates/rue_solo",
    "crates/rue_tuner",
    "crates/rue_client",
    "crates/rue_macro",
]

[workspace.lints.clippy]
pedantic = { level = "warn", priority = 1 }
perf = { level = "deny", priority = 1 }
style = { level = "warn", priority = 1 }
suspicious = { level = "warn", priority = 1 }
complexity = { level = "warn", priority = 1 }
missing_errors_doc = { level = "allow", priority = 2 }
missing_safety_doc = { level = "allow", priority = 2 }
missing_panics_doc = { level = "allow", priority = 2 }
cast_possible_truncation = { level = "allow", priority = 2 }
cast_precision_loss = { level = "allow", priority = 2 }
cast_possible_wrap = { level = "allow", priority = 2 }
cast_sign_loss = { level = "allow", priority = 2 }
too_many_lines = { level = "allow", priority = 2 }
missing_docs_in_private_items = { level = "warn", priority = 2 }

[workspace.lints.rust]
missing_docs = { level = "warn" }
