[package]
name = "rue_search"
version = "0.1.0"
edition = "2024"

[dependencies]
rue_core = { version = "0.1.0", path = "../rue_core" }
rue_nav = { version = "0.1.0", path = "../rue_nav" }
rue_eval = { version = "0.1.0", path = "../rue_eval" }
rustc-hash = "2"
rayon = "1"
smallvec = "1.15.2"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "search_bench"
harness = false

[lints]
workspace = true
