[package]
name = "rue_search"
version = "0.1.0"
edition = "2024"

[dependencies]
rue_core = { version = "0.1.0", path = "../rue_core" }
rue_eval = { version = "0.1.0", path = "../rue_eval" }
rue_nav = { version = "0.1.0", path = "../rue_nav" }
rayon = "1.12.0"
smallvec = "1.15.1"

[lints]
workspace = true
